export const RESET_STATE = 'VOLANTIS/MYDATAPREVIEW/RESET_STATE'
export const SET_VALUES = 'VOLANTIS/MYDATAPREVIEW/SET_VALUES'
export const SET_VALUE = 'VOLANTIS/MYDATAPREVIEW/SET_VALUE'

export const POST_PREVIEW_DATA_REQUEST = 'VOLANTIS/MYDATAPREVIEW/POST_PREVIEW_DATA_REQUEST'
export const POST_PREVIEW_DATA_SUCCESS = 'VOLANTIS/MYDATAPREVIEW/POST_PREVIEW_DATA_SUCCESS'
export const POST_PREVIEW_DATA_ERROR = 'VOLANTIS/MYDATAPREVIEW/POST_PREVIEW_DATA_ERROR'

export const POST_TABLE_HEADER_REQUEST = 'VOLANTIS/MYDATAPREVIEW/POST_TABLE_HEADER_REQUEST'
export const POST_TABLE_HEADER_SUCCESS = 'VOLANTIS/MYDATAPREVIEW/POST_TABLE_HEADER_SUCCESS'
export const POST_TABLE_HEADER_ERROR = 'VOLANTIS/MYDATAPREVIEW/POST_TABLE_HEADER_ERROR'

export const GET_ENTITY_REQUEST = 'VOLANTIS/MYDATAPREVIEW/GET_ENTITY_REQUEST'
export const GET_ENTITY_SUCCESS = 'VOLANTIS/MYDATAPREVIEW/GET_ENTITY_SUCCESS'
export const GET_ENTITY_ERROR = 'VOLANTIS/MYDATAPREVIEW/GET_ENTITY_ERROR'

