export const SET_VALUES = 'VOLANTIS/MYDATAPREVIEW/SET_VALUES'

export const POST_PREVIEW_DATA_REQUEST = 'VOLANTIS/MYDATAPREVIEW/POST_PREVIEW_DATA_REQUEST'
export const POST_PREVIEW_DATA_SUCCESS = 'VOLANTIS/MYDATAPREVIEW/POST_PREVIEW_DATA_SUCCESS'
export const POST_PREVIEW_DATA_ERROR = 'VOLANTIS/MYDATAPREVIEW/POST_PREVIEW_DATA_ERROR'

export const GET_ENTITY_REQUEST = 'VOLANTIS/MYDATAPREVIEW/GET_ENTITY_REQUEST'
export const GET_ENTITY_SUCCESS = 'VOLANTIS/MYDATAPREVIEW/GET_ENTITY_SUCCESS'
export const GET_ENTITY_ERROR = 'VOLANTIS/MYDATAPREVIEW/GET_ENTITY_ERROR'

