export const PUT_APP_REQUEST = 'volantis/API_MANAGEMENT/PUT_APP_REQUEST'
export const PUT_APP_SUCCESS = 'volantis/API_MANAGEMENT/PUT_APP_SUCCESS'
export const PUT_APP_ERROR = 'volantis/API_MANAGEMENT/PUT_APP_ERROR'

export const GET_PREVIEW_DATASET_REQUEST = 'volantis/API_MANAGEMENT/GET_PREVIEW_DATASET_REQUEST'
export const GET_PREVIEW_DATASET_SUCCESS = 'volantis/API_MANAGEMENT/GET_PREVIEW_DATASET_SUCCESS'
export const GET_PREVIEW_DATASET_ERROR = 'volantis/API_MANAGEMENT/GET_PREVIEW_DATASET_ERROR'
