export const PUT_APP_REQUEST = 'volantis/API_MANAGEMENT/PUT_APP_REQUEST'
export const PUT_APP_SUCCESS = 'volantis/API_MANAGEMENT/PUT_APP_SUCCESS'
export const PUT_APP_ERROR = 'volantis/API_MANAGEMENT/PUT_APP_ERROR'

export const GET_PREVIEW_DATASET_REQUEST = 'volantis/API_MANAGEMENT/GET_PREVIEW_DATASET_REQUEST'
export const GET_PREVIEW_DATASET_SUCCESS = 'volantis/API_MANAGEMENT/GET_PREVIEW_DATASET_SUCCESS'
export const GET_PREVIEW_DATASET_ERROR = 'volantis/API_MANAGEMENT/GET_PREVIEW_DATASET_ERROR'

export const SET_FIELDS = 'volantis/API_MANAGEMENT/SET_FIELDS'
export const SET_RULES = 'volantis/API_MANAGEMENT/SET_RULES'
export const SET_FIELDS_ERROR = 'volantis/API_MANAGEMENT/SET_FIELDS_ERROR'
export const SET_SHOW_MODAL = 'volantis/API_MANAGEMENT/SET_SHOW_MODAL'
export const SET_OPT_FIELDS = 'volantis/API_MANAGEMENT/SET_OPT_FIELDS'
export const SET_IS_VALID = 'volantis/API_MANAGEMENT/SET_IS_VALID'

export const GET_APP_DETAIL_REQUEST = 'volantis/API_MANAGEMENT/GET_DETAIL_REQUEST'
export const GET_APP_DETAIL_SUCCESS = 'volantis/API_MANAGEMENT/GET_DETAIL_SUCCESS'
export const GET_APP_DETAIL_ERROR = 'volantis/API_MANAGEMENT/GET_DETAIL_ERROR'
