export const GET_DATASET_REQUEST = 'volantis/API_MANAGEMENT/GET_DATASET_REQUEST'
export const GET_DATASET_SUCCESS = 'volantis/API_MANAGEMENT/GET_DATASET_SUCCESS'
export const GET_DATASET_ERROR = 'volantis/API_MANAGEMENT/GET_DATASET_ERROR'