/*
Location: pages > mydata-create > action-type.js
*/

export const POST_CREATECONNECTOR_REQUEST = 'VOLANTIS/MYDATA_CREATE/POST_CREATECONNECTOR_REQUEST'
export const POST_CREATECONNECTOR_SUCCESS = 'VOLANTIS/MYDATA_CREATE/POST_CREATECONNECTOR_SUCCESS'
export const POST_CREATECONNECTOR_ERROR = 'VOLANTIS/MYDATA_CREATE/POST_CREATECONNECTOR_ERROR'

export const POST_CHECKSQLCREDENTIAL_REQUEST = 'VOLANTIS/MYDATA_CREATE/POST_CHECKSQLCREDENTIAL_REQUEST'
export const POST_CHECKSQLCREDENTIAL_SUCCESS = 'VOLANTIS/MYDATA_CREATE/POST_CHECKSQLCREDENTIAL_SUCCESS'
export const POST_CHECKSQLCREDENTIAL_ERROR = 'VOLANTIS/MYDATA_CREATE/POST_CHECKSQLCREDENTIAL_ERROR'

export const SET_MODAL_CONFIRMATION = 'VOLANTIS/MYDATA_CREATE/SET_MODAL_CONFIRMATION'
export const SET_CREATE_TYPE = 'VOLANTIS/MYDATA_CREATE/SET_CREATE_TYPE'
export const SET_REFINED_ROLES = 'VOLANTIS/MYDATA_CREATE/SET_REFINED_ROLES'

export const SET_RULES = 'VOLANTIS/MYDATA_CREATE/SET_RULES'
export const SET_FILES = 'VOLANTIS/MYDATA_CREATE/SET_FILES'
export const RESET_FILES = 'VOLANTIS/MYDATA_CREATE/RESET_FILES'
export const SET_FILE_CHANGE = 'VOLANTIS/MYDATA_CREATE/SET_FILE_CHANGE'
export const SET_FIELDS_ERROR = 'VOLANTIS/MYDATA_CREATE/SET_FIELDS_ERROR'
export const SET_LAYOUT = 'VOLANTIS/MYDATA_CREATE/SET_LAYOUT'
export const SET_DATA = 'VOLANTIS/MYDATA_CREATE/SET_DATA'

export const RESET_FIELDS = 'VOLANTIS/MYDATA_CREATE/RESET_FIELDS'
export const SET_TOAST_CLOSE = 'VOLANTIS/MYDATA_CREATE/SET_TOAST_CLOSE'
export const SET_TOAST_OPEN = 'VOLANTIS/MYDATA_CREATE/SET_TOAST_OPEN'
