/*
Location: pages > mydata-create > action-type.js
*/

export const POST_CREATECONNECTOR_REQUEST = 'volantis/MY_DATA_CREATE/POST_CREATECONNECTOR_REQUEST'
export const POST_CREATECONNECTOR_SUCCESS = 'volantis/MY_DATA_CREATE/POST_CREATECONNECTOR_SUCCESS'
export const POST_CREATECONNECTOR_ERROR = 'volantis/MY_DATA_CREATE/POST_CREATECONNECTOR_ERROR'

export const SET_MODAL_CONFIRMATION = 'volantis/MY_DATA_CREATE/SET_MODAL_CONFIRMATION'
export const SET_AUTH_COOKIE = 'volantis/MY_DATA_CREATE/SET_AUTH_COOKIE'
export const SET_USER_INFO = 'volantis/MY_DATA_CREATE/SET_USER_INFO'
export const SET_CREATE_TYPE = 'volantis/MY_DATA_CREATE/SET_CREATE_TYPE'
export const SET_REFINED_ROLES = 'volantis/MY_DATA_CREATE/SET_REFINED_ROLES'

export const SET_RULES = 'volantis/MY_DATA_CREATE/SET_RULES'
export const SET_LAYOUT = 'volantis/MY_DATA_CREATE/SET_LAYOUT'
export const SET_DATA = 'volantis/MY_DATA_CREATE/SET_DATA'
