export const handleCreateSensor = () => (dispatch, getState) => {}
export const handleAddDatasource = () => (dispatch, getState) =>{}
export const handleNextStep = () => (dispatch, getState) => {}
export const handleBackStepTypeFile = () => (dispatch, getState) => {}
export const handleBackStep = () => (dispatch, getState) => {}
export const handleChangeInput = () => (dispatch, getState) => {}
export const handleFileChange = () => (dispatch, getState) => {}
export const renderContent = () => (dispatch, getState) => {}
export const renderModalError = () => (dispatch, getState) => {}
export const getRules = () => (dispatch, getState) => {}
export const toggleShow = () => (dispatch, getState) => {}
export const getSampleData = () => (dispatch, getState) => {}
export const getSampleDataSql = () => (dispatch, getState) => {}
export const getSampleTable = () => (dispatch, getState) => {}
export const getSensorProperties = () => (dispatch, getState) => {}
export const handleMapTableMapping = () => (dispatch, getState) => {}
export const handleChangeTypeTableMapping = () => (dispatch, getState) => {}
export const handleDeleteTableMapping = () => (dispatch, getState) => {}
export const handleChangeProps = () => (dispatch, getState) => {}
export const handleDeleteProps = () => (dispatch, getState) => {}
export const handleAddProps = () => (dispatch, getState) => {}
