export const POST_NEW_FOLDER_REQUEST = 'VOLANTIS/MYDATALIST/POST_NEW_FOLDER_REQUEST'
export const POST_NEW_FOLDER_SUCCESS = 'VOLANTIS/MYDATALIST/POST_NEW_FOLDER_SUCCESS'
export const POST_NEW_FOLDER_ERROR = 'VOLANTIS/MYDATALIST/POST_NEW_FOLDER_ERROR'
