export const GET_ENTITY_REQUEST = 'volantis/ENTITY/GET_ENTITY_REQUEST'
export const GET_ENTITY_SUCCESS = 'volantis/ENTITY/GET_ENTITY_SUCCESS'
export const GET_ENTITY_ERROR = 'volantis/ENTITY/GET_ENTITY_ERROR'

export const POST_CONNECTOR_REQUEST = 'volantis/CONNECTOR/POST_CONNECTOR_REQUEST'
export const POST_CONNECTOR_SUCCESS = 'volantis/CONNECTOR/POST_CONNECTOR_SUCCESS'
export const POST_CONNECTOR_ERROR = 'volantis/CONNECTOR/POST_CONNECTOR_ERROR'

export const GET_FUNCTION_DOC_REQUEST = 'volantis/CONNECTOR/GET_FUNCTION_DOC_REQUEST'
export const GET_FUNCTION_DOC_SUCCESS = 'volantis/CONNECTOR/GET_FUNCTION_DOC_SUCCESS'
export const GET_FUNCTION_DOC_ERROR = 'volantis/CONNECTOR/GET_FUNCTION_DOC_ERROR'

export const GET_ACCURACY_REQUEST = 'volantis/CONNECTOR/GET_ACCURACY_REQUEST'
export const GET_ACCURACY_SUCCESS = 'volantis/CONNECTOR/GET_ACCURACY_SUCCESS'
export const GET_ACCURACY_ERROR = 'volantis/CONNECTOR/GET_ACCURACY_ERROR'