export const GET_ENTITY_REQUEST = 'volantis/MYDATALIST/GET_ENTITY_REQUEST'
export const GET_ENTITY_SUCCESS = 'volantis/MYDATALIST/GET_ENTITY_SUCCESS'
export const GET_ENTITY_ERROR = 'volantis/MYDATALIST/GET_ENTITY_ERROR'

export const POST_CONNECTOR_REQUEST = 'volantis/MYDATALIST/POST_CONNECTOR_REQUEST'
export const POST_CONNECTOR_SUCCESS = 'volantis/MYDATALIST/POST_CONNECTOR_SUCCESS'
export const POST_CONNECTOR_ERROR = 'volantis/MYDATALIST/POST_CONNECTOR_ERROR'

export const GET_FUNCTION_DOC_REQUEST = 'volantis/MYDATALIST/GET_FUNCTION_DOC_REQUEST'
export const GET_FUNCTION_DOC_SUCCESS = 'volantis/MYDATALIST/GET_FUNCTION_DOC_SUCCESS'
export const GET_FUNCTION_DOC_ERROR = 'volantis/MYDATALIST/GET_FUNCTION_DOC_ERROR'

export const GET_ACCURACY_REQUEST = 'volantis/MYDATALIST/GET_ACCURACY_REQUEST'
export const GET_ACCURACY_SUCCESS = 'volantis/MYDATALIST/GET_ACCURACY_SUCCESS'
export const GET_ACCURACY_ERROR = 'volantis/MYDATALIST/GET_ACCURACY_ERROR'

export const GET_DATASET_REQUEST = 'volantis/MYDATALIST/GET_DATASET_REQUEST'
export const GET_DATASET_SUCCESS = 'volantis/MYDATALIST/GET_DATASET_SUCCESS'
export const GET_DATASET_ERROR = 'volantis/MYDATALIST/GET_DATASET_ERROR'

export const PUT_MOVE_DIRECTORY_REQUEST = 'volantis/MYDATALIST/PUT_MOVE_DIRECTORY_REQUEST'
export const PUT_MOVE_DIRECTORY_SUCCESS = 'volantis/MYDATALIST/PUT_MOVE_DIRECTORY_SUCCESS'
export const PUT_MOVE_DIRECTORY_ERROR = 'volantis/MYDATALIST/PUT_MOVE_DIRECTORY_ERROR'

export const SET_VALUE = 'my-data/list/SET_VALUE'
export const SET_VALUES = 'my-data/list/SET_VALUES'
export const SET_TOGGLE_MODAL = 'my-data/list/SET_TOGGLE_MODAL'
export const SET_TOGGLE_MODAL_CLOSE = 'my-data/list/SET_TOGGLE_MODAL_CLOSE'
export const SET_TOGGLE_MODAL_OPEN = 'my-data/list/SET_TOGGLE_MODAL_OPEN'
export const SET_PREVIEW_ASSET = 'my-data/list/SET_PREVIEW_ASSET'

export const SET_AUTH_COOKIE = 'volantis/MYDATALIST/SET_AUTH_COOKIE'
export const SET_USER_INFO = 'volantis/MYDATALIST/SET_USER_INFO'
export const SET_HEADERS = 'volantis/MYDATALIST/SET_HEADERS'
