export const GET_ENTITY_REQUEST = 'volantis/MYDATALIST/GET_ENTITY_REQUEST'
export const GET_ENTITY_SUCCESS = 'volantis/MYDATALIST/GET_ENTITY_SUCCESS'
export const GET_ENTITY_ERROR = 'volantis/MYDATALIST/GET_ENTITY_ERROR'

export const GET_FILTER_ENTITY_REQUEST = 'volantis/MYDATALIST/GET_FILTER_ENTITY_REQUEST'
export const GET_FILTER_ENTITY_SUCCESS = 'volantis/MYDATALIST/GET_FILTER_ENTITY_SUCCESS'
export const GET_FILTER_ENTITY_ERROR = 'volantis/MYDATALIST/GET_FILTER_ENTITY_ERROR'

export const POST_CONNECTOR_REQUEST = 'volantis/MYDATALIST/POST_CONNECTOR_REQUEST'
export const POST_CONNECTOR_SUCCESS = 'volantis/MYDATALIST/POST_CONNECTOR_SUCCESS'
export const POST_CONNECTOR_ERROR = 'volantis/MYDATALIST/POST_CONNECTOR_ERROR'

export const GET_FUNCTION_DOC_REQUEST = 'volantis/MYDATALIST/GET_FUNCTION_DOC_REQUEST'
export const GET_FUNCTION_DOC_SUCCESS = 'volantis/MYDATALIST/GET_FUNCTION_DOC_SUCCESS'
export const GET_FUNCTION_DOC_ERROR = 'volantis/MYDATALIST/GET_FUNCTION_DOC_ERROR'

export const GET_ACCURACY_REQUEST = 'volantis/MYDATALIST/GET_ACCURACY_REQUEST'
export const GET_ACCURACY_SUCCESS = 'volantis/MYDATALIST/GET_ACCURACY_SUCCESS'
export const GET_ACCURACY_ERROR = 'volantis/MYDATALIST/GET_ACCURACY_ERROR'

export const GET_DATASET_REQUEST = 'volantis/MYDATALIST/GET_DATASET_REQUEST'
export const GET_DATASET_SUCCESS = 'volantis/MYDATALIST/GET_DATASET_SUCCESS'
export const GET_DATASET_ERROR = 'volantis/MYDATALIST/GET_DATASET_ERROR'

export const PUT_MOVE_DIRECTORY_REQUEST = 'volantis/MYDATALIST/PUT_MOVE_DIRECTORY_REQUEST'
export const PUT_MOVE_DIRECTORY_SUCCESS = 'volantis/MYDATALIST/PUT_MOVE_DIRECTORY_SUCCESS'
export const PUT_MOVE_DIRECTORY_ERROR = 'volantis/MYDATALIST/PUT_MOVE_DIRECTORY_ERROR'

export const POST_MOVE_TRASH_REQUEST = 'volantis/MYDATALIST/POST_MOVE_TRASH_REQUEST'
export const POST_MOVE_TRASH_SUCCESS = 'volantis/MYDATALIST/POST_MOVE_TRASH_SUCCESS'
export const POST_MOVE_TRASH_ERROR = 'volantis/MYDATALIST/POST_MOVE_TRASH_ERROR'

export const POST_RESTORE_TRASH_REQUEST = 'volantis/MYDATALIST/POST_RESTORE_TRASH_REQUEST'
export const POST_RESTORE_TRASH_SUCCESS = 'volantis/MYDATALIST/POST_RESTORE_TRASH_SUCCESS'
export const POST_RESTORE_TRASH_ERROR = 'volantis/MYDATALIST/POST_RESTORE_TRASH_ERROR'

export const GET_TRASH_LIST_REQUEST = 'volantis/MYDATALIST/GET_TRASH_LIST_REQUEST'
export const GET_TRASH_LIST_SUCCESS = 'volantis/MYDATALIST/GET_TRASH_LIST_SUCCESS'
export const GET_TRASH_LIST_ERROR = 'volantis/MYDATALIST/GET_TRASH_LIST_ERROR'

export const PUT_SYNC_DATASOURCE_REQUEST = 'volantis/MYDATALIST/PUT_SYNC_DATASOURCE_REQUEST'
export const PUT_SYNC_DATASOURCE_SUCCESS = 'volantis/MYDATALIST/PUT_SYNC_DATASOURCE_SUCCESS'
export const PUT_SYNC_DATASOURCE_ERROR = 'volantis/MYDATALIST/PUT_SYNC_DATASOURCE_ERROR'

export const GET_FILTERED_APP_LIST_REQUEST = 'volantis/MYDATALIST/GET_FILTERED_APP_LIST_REQUEST'
export const GET_FILTERED_APP_LIST_SUCCESS = 'volantis/MYDATALIST/GET_FILTERED_APP_LIST_SUCCESS'
export const GET_FILTERED_APP_LIST_ERROR = 'volantis/MYDATALIST/GET_FILTERED_APP_LIST_ERROR'

export const SET_VALUE = 'volantis/MYDATALIST/SET_VALUE'
export const SET_VALUES = 'volantis/MYDATALIST/SET_VALUES'
export const SET_TOGGLE_MODAL = 'volantis/MYDATALIST/SET_TOGGLE_MODAL'
export const SET_TOGGLE_MODAL_CLOSE = 'volantis/MYDATALIST/SET_TOGGLE_MODAL_CLOSE'
export const SET_TOGGLE_MODAL_OPEN = 'volantis/MYDATALIST/SET_TOGGLE_MODAL_OPEN'
export const SET_PREVIEW_MODEL = 'volantis/MYDATALIST/SET_PREVIEW_MODEL'
export const SET_EMPTY_ENTITIES = 'volantis/MYDATALIST/SET_EMPTY_ENTITIES'

export const SET_AUTH_COOKIE = 'volantis/MYDATALIST/SET_AUTH_COOKIE'
export const SET_USER_INFO = 'volantis/MYDATALIST/SET_USER_INFO'
export const SET_HEADERS = 'volantis/MYDATALIST/SET_HEADERS'
export const SET_DOUBLE_CLICK = 'volantis/MYDATALIST/SET_DOUBLE_CLICK'

export const GET_MODEL_REQUEST = 'volantis/MYDATALIST/GET_MODEL_REQUEST'
export const GET_MODEL_SUCCESS = 'volantis/MYDATALIST/GET_MODEL_SUCCESS'
export const GET_MODEL_ERROR = 'volantis/MYDATALIST/GET_MODEL_ERROR'

export const GET_PRETRAINED_MODEL_REQUEST = 'volantis/MYDATALIST/GET_PRETRAINED_MODEL_REQUEST'
export const GET_PRETRAINED_MODEL_SUCCESS = 'volantis/MYDATALIST/GET_PRETRAINED_MODEL_SUCCESS'
export const GET_PRETRAINED_MODEL_ERROR = 'volantis/MYDATALIST/GET_PRETRAINED_MODEL_ERROR'

export const GET_PIPELINE_REQUEST = 'volantis/MYDATALIST/GET_PIPELINE_REQUEST'
export const GET_PIPELINE_SUCCESS = 'volantis/MYDATALIST/GET_PIPELINE_SUCCESS'
export const GET_PIPELINE_ERROR = 'volantis/MYDATALIST/GET_PIPELINE_ERROR'

export const SET_TOGGLE_MODAL_CONFIRMATION_CLOSE = 'volantis/MYDATALIST/SET_TOGGLE_MODAL_CONFIRMATION_CLOSE'
export const SET_TOGGLE_MODAL_CONFIRMATION_OPEN = 'volantis/MYDATALIST/SET_TOGGLE_MODAL_CONFIRMATION_OPEN'
