export const GET_DATASET_REQUEST = 'volantis/API_MANAGEMENT/GET_DATASET_REQUEST'
export const GET_DATASET_SUCCESS = 'volantis/API_MANAGEMENT/GET_DATASET_SUCCESS'
export const GET_DATASET_ERROR = 'volantis/API_MANAGEMENT/GET_DATASET_ERROR'

export const SET_AUTH_COOKIE = 'volantis/API_MANAGEMENT/SET_AUTH_COOKIE'
