export const GET_APP_LIST_REQUEST = 'volantis/API_MANAGEMENT/GET_LIST_REQUEST'
export const GET_APP_LIST_SUCCESS = 'volantis/API_MANAGEMENT/GET_LIST_SUCCESS'
export const GET_APP_LIST_ERROR = 'volantis/API_MANAGEMENT/GET_LIST_ERROR'
export const SET_SEARCH = 'volantis/API_MANAGEMENT/SET_SEARCH'

export const GET_FILTERED_APP_LIST_REQUEST = 'volantis/API_MANAGEMENT/GET_FILTERED_LIST_REQUEST'
export const GET_FILTERED_APP_LIST_SUCCESS = 'volantis/API_MANAGEMENT/GET_FILTERED_LIST_SUCCESS'
export const GET_FILTERED_APP_LIST_ERROR = 'volantis/API_MANAGEMENT/GET_FILTERED_LIST_ERROR'
export const SET_SELECTED_APP = 'volantis/API_MANAGEMENT/SET_SELECTED_APP'
